Repository ember-engines/ember-asset-loader, pull requests merged in 2022-05, with the labels that each got.

#127 Add support code for future ember-auto-import versions to be used within lazy Ember Engines
  addon/services/asset-loader.js
Labels: enhancement

#130 Drop Node < 14
  README.md
  package.json
  yarn.lock
Labels: breaking

#132 update dependencies
  index.js
  lib/manifest-generator.js
  package.json
  yarn.lock
Labels: enhancement

#128 Switch CI from Travis to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  README.md
  addon/services/asset-loader.js
  package.json
  yarn.lock
Labels: internal

#135 replace ember-cli-eslint with eslint
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  package.json
  testem.sauce.js
  tests/.eslintrc.js
  tests/dummy/config/environment.js
  tests/dummy/lib/test-generator-plugin/index.js
  tests/dummy/public/test-dist/loaded-asset-state/loaded-asset-state.js
  yarn.lock
Labels: dependencies

#137 replace ember-cli-qunit with ember-qunit
  package.json
  tests/index.html
  tests/test-helper.js
  yarn.lock
Labels: dependencies

#138 Introduce prettier per latest addon blueprint
  .eslintrc.js
  .npmignore
  .prettierignore
  .prettierrc.js
  addon-test-support/loaded-asset-state.js
  addon-test-support/preload-assets.js
  addon/errors/asset-load.js
  addon/errors/bundle-load.js
  addon/errors/load.js
  addon/loaders/css.js
  addon/loaders/js.js
  addon/loaders/utilities.js
  addon/services/asset-loader.js
  app/config/asset-manifest.js
  app/instance-initializers/load-asset-manifest.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  lib/asset-manifest-generator.js
  lib/asset-manifest-inserter.js
  lib/generate-asset-manifest.js
  lib/manifest-generator.js
  lib/meta-handler.js
  lib/node-asset-manifest-generator.js
  lib/utils/find-host.js
  node-tests/.eslintrc.js
  node-tests/asset-manifest-generator-test.js
  node-tests/asset-manifest-inserter-tests.js
  node-tests/generate-asset-manifest-test.js
  node-tests/manifest-generator-test.js
  node-tests/meta-handler-tests.js
  package.json
  testem.js
  testem.sauce.js
  tests/acceptance/asset-load-test.js
  tests/dummy/app/app.js
  tests/dummy/app/initializers/router-ext.js
  tests/dummy/app/router.js
  tests/dummy/app/routes/asset-error.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/dummy/lib/test-generator-plugin/index.js
  tests/dummy/public/test-dist/loaded-asset-state/loaded-asset-state.js
  tests/dummy/public/unit-test.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/resolver.js
  tests/unit/asset-manifest-test.js
  tests/unit/errors/asset-load-test.js
  tests/unit/errors/bundle-load-test.js
  tests/unit/errors/load-test.js
  tests/unit/services/asset-loader-test.js
  tests/unit/test-helpers/loaded-asset-state-test.js
  yarn.lock
Labels: internal

#139 Introduce `eslint-plugin-qunit` per latest addon blueprint
  .eslintrc.js
  package.json
  tests/acceptance/asset-load-test.js
  tests/unit/asset-manifest-test.js
  tests/unit/errors/asset-load-test.js
  tests/unit/errors/bundle-load-test.js
  tests/unit/errors/load-test.js
  tests/unit/services/asset-loader-test.js
  yarn.lock
Labels: internal

#140 Introduce `ember-template-lint` per latest addon blueprint
  .template-lintrc.js
  package.json
  yarn.lock
Labels: internal
